name: "treefmt GitHub Action"
description: "Installs and runs treefmt on your repository"
author: "Ian Becker"
branding:
  icon: "align-justify"
  color: "orange"
inputs:
  version:
    description: "The version of treefmt to install"
    required: false
    default: "latest"
  github_token:
    description: "GitHub token for accessing the API"
    required: true
  config_file:
    description: "Path to the treefmt configuration file"
    required: false
    default: "treefmt.toml"
  allow_missing_formatter:
    description: "Do not exit with error if a configured formatter is missing"
    required: false
    default: "false"
  working_dir:
    description: "Run as if treefmt was started in the specified working directory instead of the current working directory"
    required: false
    default: "."
  ci:
    description: "Runs treefmt in a CI mode, enabling --no-cache, --fail-on-change and adjusting some other settings best suited to a CI use case"
    required: false
    default: "false"
  no_cache:
    description: "Ignore the evaluation cache entirely. Useful for CI"
    required: false
    default: "false"
  fail_on_change:
    description: "Exit with error if any changes were made. Useful for CI"
    required: false
    default: "true"
  formatters:
    description: "Specify formatters to apply. Defaults to all formatters"
    required: false
    default: ""
  tree_root:
    description: "The root directory from which treefmt will start walking the filesystem"
    required: false
    default: ""
  tree_root_file:
    description: "File to search for to find the project root (if --tree_root is not passed)"
    required: false
    default: ""
  walk:
    description: "The method used to traverse the files within --tree_root. Supports 'auto', 'git' or 'filesystem'"
    required: false
    default: "auto"
  verbose:
    description: "Set the verbosity of logs"
    required: false
    default: "0"
  on_unmatched:
    description: "Log paths that did not match any formatters at the specified log level"
    required: false
    default: "warn"
  clear_cache:
    description: "Reset the evaluation cache. Use in case the cache is not precise enough"
    required: false
    default: "false"
  cpu_profile:
    description: "The file into which a CPU profile will be written"
    required: false
    default: ""
  excludes:
    description: "Exclude files or directories matching the specified globs"
    required: false
    default: ""
  stdin:
    description: "Format the context passed in via stdin"
    required: false
    default: "false"
  init:
    description: "Create a treefmt.toml file in the current directory"
    required: false
    default: "false"
runs:
  using: "node20"
  main: "dist/index.js"
