[formatter.typescript]
command = "biome"
options = ["format", "--write", "--no-errors-on-unmatched"]
includes = ["*.ts", "*.json"]
excludes = ["dist/*", "node_modules/*"]

[formatter.toml]
command = "taplo"
options = ["fmt"]
includes = ["*.toml", "*.editorconfig"]
