name: Test treefmt Action

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        arch: [x86_64, arm64]
        test-case:
          - name: 'Default settings'
            version: 'latest'
            ci: 'true'
          - name: 'Specify version 2.1.0'
            version: '2.1.0'
            ci: 'true'
          - name: 'Custom config file'
            config_file: 'treefmt.toml'
          - name: 'Allow missing formatters'
            allow_missing_formatter: 'true'
          - name: 'Run in specific working directory'
            working_dir: '.'
          - name: 'Disable cache'
            no_cache: 'true'
          - name: 'Do not fail on change'
            fail_on_change: 'false'
          - name: 'Run specific formatters'
            formatters: 'typescript,toml'
          - name: 'Increase verbosity'
            verbose: '2'
          - name: 'Clear cache before run'
            clear_cache: 'true'
          - name: 'Exclude certain paths'
            excludes: 'docs/**,tests/**'
          - name: 'Initialize treefmt configuration'
            init: 'true'
    name: ${{ matrix.test-case.name }} on ${{ matrix.os }} ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v2
      - uses: biomejs/setup-biome@v2.2.1
      - uses: uncenter/setup-taplo@v1.0.8
      - name: Run treefmt Action
        uses: ./
        with:
          version: ${{ matrix.test-case.version }}
          config_file: ${{ matrix.test-case.config_file }}
          allow_missing_formatter: ${{ matrix.test-case.allow_missing_formatter }}
          working_dir: ${{ matrix.test-case.working_dir }}
          no_cache: ${{ matrix.test-case.no_cache }}
          fail_on_change: ${{ matrix.test-case.fail_on_change }}
          formatters: ${{ matrix.test-case.formatters }}
          verbose: ${{ matrix.test-case.verbose }}
          clear_cache: ${{ matrix.test-case.clear_cache }}
          excludes: ${{ matrix.test-case.excludes }}
          init: ${{ matrix.test-case.init }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
  marketplace-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: biomejs/setup-biome@v2.2.1
      - uses: uncenter/setup-taplo@v1.0.8
      - name: Run treefmt Action from Marketplace
        uses: isbecker/treefmt-action@v1.3.0
        with:
          version: 'latest'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          ci: 'true'